#!/bin/bash

function pause() {
read -p ""
}

function ImHere() {
echo -e "
*******************
** Hello World ! **
*******************"
}

function ToHtml ()
{
sed 's/à/\&agrave;/g
s/â/\&acirc;/g
s/ä/\&auml;/g
s/ç/\&ccedil;/g
s/è/\&egrave;/g
s/é/\&eacute;/g
s/ê/\&ecirc;/g
s/ë/\&euml;/g
s/î/\&icirc;/g
s/ï/\&iuml;/g
s/ù/\&ugrave;/g
s/ü/\&uuml;/g
s/û/\&ucirc;/g'
}

# Vars
BASEDIR=$PWD
QRDIR="$BASEDIR/.tmp/qr"
PDFDIR="$BASEDIR/.tmp/pdf"
mkqrdir="$HOME/.makeqrcodes"


# Dirs
fn_mkdir() {
mkdir -p ".tmp/qr"
mkdir -p ".tmp/pdf"
}

fn_rmdir() {
rm -r "$BASEDIR/.tmp"
}

fn_qrcode() {
#QRENCODE
i=1
while read stringcode ; do
code=$(printf "%0.3d.png" $i)
echo -e "Generating $code for QRCode $stringcode"
qrencode -s 25 -l H -m 1 --output=".tmp/qr/$code" $stringcode
((i++))
done < "$qrsrc"
unset i
echo ""
}


fn_makehtmltopdf() {
#HTML FILE
i=1
cd .tmp/qr

for image in *; do
billet=$(printf "%0.3d" $i)
echo -e "Adding Billet n°$billet with $image to the tmp html file"
echo -e "<html><head><style>
  .break {
    page-break-inside: avoid;
	  }
	</style></head><body>

	<center><div class=\"break\"><br/>
	<h1 style=\"font-size:100px\"><center>$TITLE<center></h1>
	 <img src=\"qr/$image\"/></div>
	<h1 style=\"font-size:50px\"><center>Billet n&deg;$billet<center></h1>
	</center></html>"  | ToHtml > ../HTMLQRCODE.html
	wkhtmltopdf "../HTMLQRCODE.html" "$PDFDIR/QRCODES-$billet.pdf" &>/dev/null
((i++))
done
unset i
echo -e "Building PDF file from the HTML one..."
pdftk "$PDFDIR"/*.pdf cat output "$BASEDIR/QRCODES_PDF.pdf"


cd "$BASEDIR"
}

lprfunction() { ################ INCOMPLET
################################### CETTE PARTIE DU SCRIPT
################################### EST DESTINÉE À CRÉER
################################### UNE OUTPUT TERMINALE
################################### AVEC $printperpage PAGES PAR SHEET

################################### USAGE DE LP ???

# Créer une variable sur le nombre de billet par page ?
	# 9 per page est acceptable
lpr -o number-up=$printperpage -P PDF QRCODES_PDF.pdf
echo -e "Printing in PDF ($printperpage tickets per page)..."

while lpstat | grep -q ^PDF-; do
sleep 2
done
echo -e "\nLa tâche d'impression PDF est terminée"
mv "$HOME/PDF/QRCODES_PDF.pdf" "$BASEDIR/QRCODES_PDF.pdf"
}



TIMESTART=$(date +"%r")
while [[ $# -gt 0 ]]; do
    case "$1" in
    -t) 
	TITLE=$2
        shift 
	;;
    -qr)
        if [[ -r $2 ]]; then
	qrsrc=$2
        fi
        shift
        ;;
    -printper)
	if [[ $2 = 2 || $2 = 4 || $2 = 6 || $2 = 9 || $2 = 16 ]]; then
	printper=1
	printperpage=$2
	else
	printper="ERROR"
	fi
	;;
    ""|*) ;;
    esac
    shift
done


if [[ $qrsrc != "" && $TITLE != "" && $printper != "ERROR" ]]; then
fn_mkdir && fn_qrcode && fn_makehtmltopdf
fn_rmdir

if [[ $printper = 1 ]]; then
	lprfunction
fi


TIMEEND=$(date +'%r')
echo -e "\n\nStart : $TIMESTART"
echo -e "End   : $TIMEEND"

else
echo -e "Arguments invalides...
\$ $(basename $0) -t TITLE -qr FILE [-printper {2,4,9}]
	TITLE = Titre de l'événement
	FILE = nom du fichier contenant les entrées des QR CODES.
	
	[-printper {2,4,6,9,16}] = Nombre de billet par feuille A4. Défaut = 1"
exit 1
fi

exit 0
